name: Run Daily Notebook

on:
  schedule:
    - cron: '0 23 * * *'  # Run at 11 PM every day
  workflow_run:
    workflows: ["Run Daily Notebook"]

jobs:
  run-notebook:
    runs-on: ubuntu-latest  # Using a Linux-based VM
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Use the version compatible with your Python environment

      - name: Run Jupyter Notebook
        run: |
          python -m nbconvert --execute --to notebook simplied_daily_fois_alert.ipynb
        env:
          JUPYTER_ENABLE_LAB: 'true'  # Optional: Enables JupyterLab if needed
